name: pytest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [3.7, 3.8, 3.9]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'

